apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Référence vers la base
resources:
  - ../../base

# Namespace cible pour cet overlay
namespace: todo-api-dev

# Labels ajoutés à toutes les ressources de cet overlay
labels:
  - pairs:
      environment: dev
    includeSelectors: true

# Liste des patches à appliquer
patches:
  - path: patch-replicas.yaml